export { Quizpage } from './Quizpage/Quizpage'
export { Homepage } from './HomePage/Homepage'
export { Scoreboard } from './Scoreboard/Scoreboard'
export { Report } from './Report/Report'
export { Login } from './Login/Login'
export { SignUp } from './Signup/Signup'
export { Userdetails } from './UserDetails/userdetails'